services:
  db:
    image: postgres:15
    container_name: fidex_db
    restart: always
    ports:
      - "51214:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fidex_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: