import React from "react";
import { determineTextColor } from "./colors";
import {
  IconApple,
  IconBolt,
  IconBook,
  IconQuestionMark,
  IconBread,
  IconBus,
  IconBuildingBank,
  IconCar,
  IconCat,
  IconCoffee,
  IconCoins,
  IconCreditCard,
  IconDeviceGamepad2,
  IconDog,
  IconDroplet,
  IconFlame,
  IconGift,
  IconHome,
  IconMedicalCross,
  IconMovie,
  IconMusic,
  IconPill,
  IconPigMoney,
  IconPlane,
  IconReceipt,
  IconSchool,
  IconShirt,
  IconShoppingCart,
  IconShoppingBag,
  IconStethoscope,
  IconTrain,
  IconToolsKitchen2,
  IconWallet,
  IconCashBanknote,
  IconTransferIn,
  IconTax,
} from "@tabler/icons-react";

type TablerIconComponent = typeof IconQuestionMark;

export const iconMap: Record<string, TablerIconComponent> = {
  IconQuestionMark,
  IconWallet,
  IconCreditCard,
  IconCashBanknote,
  IconBuildingBank,
  IconPigMoney,
  IconCoins,
  IconReceipt,
  IconBus,
  IconTrain,
  IconCar,
  IconPlane,
  IconHome,
  IconBolt,
  IconDroplet,
  IconFlame,
  IconCoffee,
  IconToolsKitchen2,
  IconMedicalCross,
  IconStethoscope,
  IconPill,
  IconSchool,
  IconBook,
  IconShirt,
  IconGift,
  IconMusic,
  IconDeviceGamepad2,
  IconShoppingBag,
  IconMovie,
  IconShoppingCart,
  IconTransferIn,
  IconTax,
  IconBread,
  IconApple,
  IconDog,
  IconCat,
};

export const ACCOUNT_ICON_OPTIONS = [
  "IconWallet",
  "IconCreditCard",
  "IconCashBanknote",
  "IconBuildingBank",
  "IconPigMoney",
  "IconCoins",
  "IconReceipt",
  "IconQuestionMark",
] as const;

export const CATEGORY_ICON_OPTIONS = [
  "IconBread",
  "IconApple",
  "IconShoppingCart",
  "IconShoppingBag",
  "IconCoffee",
  "IconToolsKitchen2",
  "IconCar",
  "IconBus",
  "IconTrain",
  "IconPlane",
  "IconHome",
  "IconBolt",
  "IconDroplet",
  "IconFlame",
  "IconMedicalCross",
  "IconStethoscope",
  "IconPill",
  "IconSchool",
  "IconBook",
  "IconMovie",
  "IconMusic",
  "IconDeviceGamepad2",
  "IconShirt",
  "IconGift",
  "IconDog",
  "IconCat",
  "IconTransferIn",
  "IconTax",
  "IconCashBanknote",
  "IconQuestionMark",
] as const;

export function renderIconByName(
  name?: string | null,
  backgroundColor?: string | null,
  dynamicColor?: boolean
): React.ReactElement {
  const Comp = (name && iconMap[name]) || iconMap["IconQuestionMark"];
  const textColor = determineTextColor(backgroundColor);
  return React.createElement(Comp, { className: `h-5 w-5`, style: dynamicColor ? { color: textColor } : undefined });
}
